---
title: "control_plot_albedo_processing"
author: "Erika Lee"
date: "2024-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#packages
library(tidyverse)
library(lubridate)
library(ggplot2)
library(stringr)
library(readxl)
library(rstatix)
library(sf)
library(terra)
library(plotly)
library(RColorBrewer) 
library(plotly)
library(patchwork)
library(ggpubr)

setwd("/Volumes/wcnr-network/Research/Kampf/Private/field_data")
```

```{r}
#read in persistent control plot data
library(readxl)
library(dplyr)
library(lubridate)

pers_control_all <- read_excel("nsf/albedo/albedo_experimental_plots/pers_experimental_plots.xlsx") %>%
  # Convert Date to the correct date format
  mutate(date = ymd(date)) %>%
  # Ensure Time is formatted correctly (remove any weird date part)
  mutate(time = format(as.POSIXct(time, format = "%H:%M:%S"), format = "%H:%M:%S")) %>%
  # Combine date and time into a datetime column
  mutate(datetime = ymd_hms(paste(date, time))) %>%
  # Assign MST time zone to the datetime column
  mutate(datetime = force_tz(datetime, tzone = "MST")) %>%
  # Rearrange columns
  select(c(site_name, concentration, id, date, time, datetime, everything()))


#read in transitional control plots
trans_control_all <- read_excel("nsf/albedo/albedo_experimental_plots/trans_experimental_plots.xlsx") %>%
  # Convert Date to the correct date format
  mutate(date = ymd(date)) %>%
  # Ensure Time is formatted correctly (remove any weird date part)
  mutate(time = format(as.POSIXct(time, format = "%H:%M:%S"), format = "%H:%M:%S")) %>%
  mutate(datetime = ymd_hms(paste(date, time))) %>%
  # Assign MST time zone to the datetime column
  mutate(datetime = force_tz(datetime, tzone = "MST")) %>%
  select(c(site_name, concentration, id, date, time, datetime, everything()))
```

```{r}
#plotting albedo for control plots

##this plot does not really make sense yet, may need to mess around with what is being facet wrapped + the concentration column
pers_control_snow_albedo_all_plot <- ggplot(data = pers_control_all) +
  geom_bar(aes(x = id, y = albedo, fill = soot_mass_g), alpha = 0.7, position = "dodge") +
  labs(
    title = "Persistent Control Plot Albedo Data",
    x = "Site Name",
    y = "Albedo (unitless)", 
    fill = "Soot Mass Added (g)"
  ) +
  theme_minimal() +
  facet_wrap(~concentration + date)
  
pers_control_snow_albedo_all_plot

# Define a custom vector of colors from the "Spectral" palette
custom_colors <- c("#D95F02", "#E6AB02", "#66A61E")

V2_pers_control_albedo_all_plot <- ggplot(data = pers_control_all) +
  geom_bar(aes(x = id, y = albedo, fill = concentration), alpha = 0.9, position = "dodge", stat = "identity") +
  labs(
    title = "Persistent Control Plot Albedo Data",
    x = "Site Name",
    y = "Albedo (unitless)", 
    fill = "Concentration of Soot Added"
  ) +
  theme_minimal() +
  facet_wrap(~date) +
  scale_fill_manual(values = custom_colors)
  
V2_pers_control_albedo_all_plot

# Convert ggplot to Plotly plot
pers_control_albedo_plotly <- ggplotly(V2_pers_control_albedo_all_plot)

pers_control_albedo_plotly

#creating a snow depth plot for the same information, but instead of albedo doing snow depth
## Define a custom vector of colors from the "Spectral" palette
custom_colors_2 <- brewer.pal(11, "BrBG")[10:8]

pers_control_snowd_all_plot <- ggplot(data = pers_control_all) +
  geom_bar(aes(x = id, y = snow_depth_cm, fill = concentration), alpha = 0.9, position = "dodge", stat = "identity") +
  labs(
    x = "Site Name",
    y = "Snow Depth (cm)", 
    fill = "Concentration of Soot Added"
  ) +
  theme_minimal() +
  facet_wrap(~date) +
  scale_fill_manual(values = custom_colors_2)

pers_control_snowd_all_plot

#combinging ggplots 
pers_b_control_all_V2 <- V2_pers_control_albedo_all_plot + pers_control_snowd_all_plot + plot_layout(nrow = 2)

print(pers_b_control_all_V2)
```

```{r}
##NONE OF THIS IS WORKING, DO NOT RUN
# Convert ggplot to Plotly plot
pers_control_snowd_all_plotly <- ggplotly(pers_control_snowd_all_plot)

pers_control_snowd_all_plotly

#combining albedo and snow depth plots - NOT WORKING
pers_b_control_allplots <- subplot(pers_control_albedo_plotly, pers_control_snowd_all_plotly, nrows = 2, shareX = TRUE)

# Add individual y-axis titles - NOT WORKING
pers_b_control_allplots <- layout(pers_b_control_allplots,
                                  title = list(text = "Persistent Control Plots Albedo and Snow Depth"),
                                  xaxis = list(title = "Plot Name"), 
                                  yaxis = list(title = "Albedo (unitless)"), 
                                  yaxis2 = list(title = "Snow Depth (cm)"))

pers_b_control_allplots
```

Transitional Plots

```{r}
#colors for plots
#to display the colors
display.brewer.pal(n = 8, name = "Dark2")

#to get the hex number of the colors
brewer.pal(n = 8, name = "Dark2")

custom_colors <- brewer.pal(c("#D95F02", "#E6AB02", "#66A61E"))
```

```{r}

trans_control_albedo_all_plot <- ggplot(data = trans_control_all) +
  geom_bar(aes(x = id, y = albedo, fill = concentration), alpha = 0.9, position = "dodge", stat = "identity") +
  labs(
    title = "Transitional Control Plot Albedo Data",
    x = "Site Name",
    y = "Albedo (unitless)", 
    fill = "Concentration of Soot Added"
  ) +
  theme_minimal() +
  facet_wrap(~date) +
  scale_fill_manual(values = custom_colors)
  
trans_control_albedo_all_plot

# Convert ggplot to Plotly plot
trans_control_albedo_plotly <- ggplotly(trans_control_albedo_all_plot)

trans_control_albedo_plotly

#creating a snow depth plot for the same information, but instead of albedo doing snow depth
## Define a custom vector of colors from the "Spectral" palette
custom_colors_2 <- brewer.pal(11, "BrBG")[10:8]

trans_control_snowd_all_plot <- ggplot(data = trans_control_all) +
  geom_bar(aes(x = id, y = snow_depth_cm, fill = concentration), alpha = 0.9, position = "dodge", stat = "identity") +
  labs(
    x = "Site Name",
    y = "Snow Depth (cm)", 
    fill = "Concentration of Soot Added"
  ) +
  theme_minimal() +
  facet_wrap(~date) +
  scale_fill_manual(values = custom_colors_2)

trans_control_snowd_all_plot

#Combining ggplots and export to see if the layout works - it does, they are just not interactive
trans_b_control_all <- trans_control_albedo_all_plot + trans_control_snowd_all_plot + plot_layout(nrow = 2)

print(trans_b_control_all)

print(pers_b_control_all_V2)
```

Creating Box Plots of Range

```{r}
#persistent box plots
#this approach is not best
pers_control_boxplot <- ggplot(pers_control_all, aes(x = site_name, y = albedo)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "All Persistent Control Plots", x = "site_name", y = "albedo")

print(pers_control_boxplot)

##this approach seems to have the best data display
pers_control_boxplots_byconc <- ggplot(pers_control_all, aes(x = concentration, y = albedo)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Persistent Control Boxplots by Concentration", x = "Concentration", y = "Albedo (unitless)") +
  facet_wrap(~ date)

print(pers_control_boxplots_byconc)

#transitional
trans_control_boxplots_byconc <- ggplot(trans_control_all, aes(x = concentration, y = albedo)) +
  geom_boxplot() +
  theme_minimal() +
  labs(title = "Transitional Control Boxplots by Concentration", x = "Concentration", y = "Albedo (unitless)") +
  facet_wrap(~ date)

print(trans_control_boxplots_byconc)
```

```{r}
#saving control box plots
# Save the plot as a PNG file to working directory
ggsave("pers_control_boxplots_byconc.png", plot = pers_control_boxplots_byconc, width = 8, height = 6, dpi = 300, bg = "white")

ggsave("trans_control_boxplots_byconc.png", plot = pers_control_boxplots_byconc, width = 8, height = 6, dpi = 300, bg = "white")
```

```{r}
#exporting individual plots because I cannot get the combination plots to work well

##persistent plots
# Save the plot as a PNG file to working directory
ggsave("pers_b_control_all.png", plot = pers_b_control_all_V2, width = 8, height = 6, dpi = 300, bg = "white")

ggsave("trans_b_control_all.png", plot = trans_b_control_all, width = 8, height = 6, dpi = 300, bg = "white")

print(trans_b_control_all)

print(pers_b_control_all_V2)
```

Different Plotting Approach

```{r}
#creating monthly dataframes
pers_control_april <- pers_control_all %>%
  filter(date == c('2024-04-05', '2024-04-29'))

pers_control_april05 <- pers_control_all %>%
  filter(date == '2024-04-05')

pers_control_april29 <- pers_control_all %>%
  filter(date == '2024-04-29')

pers_control_may <- pers_control_all %>%
  filter(date == c('2024-05-13', '2024-05-31'))

pers_control_may13 <- pers_control_all %>%
  filter(date == '2024-05-13')

pers_control_may31 <- pers_control_all %>%
  filter(date == '2024-05-31')

trans_control_march20 <- trans_control_all %>%
  filter(date == '2024-03-20')

trans_control_april29 <- trans_control_all %>%
  filter(date == '2024-04-20')

trans_control_may13 <- trans_control_all %>%
  filter(date == '2024-05-13')
```

Plotting by Mean Conc by Date

```{r}
#making one large dataframe so I can facet wrap by snowzone
## adding in zone column
trans_control_all <- trans_control_all %>%
  mutate(zone = "transitional")

pers_control_all <- pers_control_all %>%
  mutate(zone = "persistent")

combined_zone_control_data <- rbind(pers_control_all, trans_control_all)
```

```{r}
#COMBINED DATA FRAME PLOTS
##combined albedo plots
all_control_albedo_plot <- ggplot(data = combined_zone_control_data) +
  geom_col(aes(x = factor(date), y = mean_albedo_bydate, fill = concentration), alpha = 0.7, width = 0.6, position = "dodge") +
  labs(
    title = "Control Plots Albedo",
    x = "Date of Observation",
    y = "Mean Albedo by Concentration (unitless)", fill = "Concentration of Soot Added"  # Rename the legend title here
  ) +
  theme_bw() +
  scale_fill_manual(values = c("high (3 g)" = "#D95F02", "low (1 g)" = "#E6AB02", "none" = "#66A61E")) +
  facet_wrap(~zone, scales = "free_x")
#set scales = "free_x" for the facet wrap to let the individual plots set their own x scale

all_control_albedo_plot

##combined snowdepth plots
all_control_snowdepth_plots <- ggplot() +
  geom_col(data = combined_zone_control_data, aes(x = factor(date), y = mean_snowdepth_bydate, fill = concentration), alpha = 0.7, width = 0.6, position = "dodge") +
  labs(
    title = "Control Plot Depths",
    x = "Date of Observation",
    y = "Mean Snow Depth (cm)", 
    fill = "Concentration of Soot Added"  # Rename the legend title here
  ) +
  theme_bw() +
  scale_fill_manual(values = c("high (3 g)" = "#D95F02", "low (1 g)" = "#E6AB02", "none" = "#66A61E")) +
  facet_wrap(~zone, scales = "free_x")

all_control_snowdepth_plots
```

```{r}
#INDIVIDUAL DATA FRAME PLOTS
#persistent control albedo
pers_controlalb_all_plot <- ggplot() +
  geom_col(data = pers_control_all, aes(x = factor(date), y = mean_albedo_bydate, fill = concentration), alpha = 0.7, width = 0.6, position = "dodge") +
  labs(
    title = "Persistent Control Plots Albedo",
    x = "Date of Observation",
    y = "Mean Albedo by Concentration (unitless)"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("high (3 g)" = "red", "low (1 g)" = "blue", "none" = "grey"))

pers_controlalb_all_plot

#transitional control albedo
trans_controlalb_all_plot <- ggplot() +
  geom_col(data = trans_control_all, aes(x = factor(date), y = mean_albedo_bydate, fill = concentration), alpha = 0.7, width = 0.6, position = "dodge") +
  labs(
    title = "Transitional Control Plots Albedo",
    x = "Date of Observation",
    y = "Mean Albedo by Concentration (unitless)"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("high (3 g)" = "red", "low (1 g)" = "blue", "none" = "grey"))

trans_controlalb_all_plot
```

```{r}
#plotting snow depths
#persistent control albedo
pers_controlsnowdepth_all_plot <- ggplot() +
  geom_col(data = pers_control_all, aes(x = factor(date), y = mean_snowdepth_bydate, fill = concentration), alpha = 0.4, width = 0.6, position = "dodge") +
  labs(
    #title = "Persistent Control Plots Snow Depth",
    x = "Date of Observation",
    y = "Mean Snow Depth by Concentration (cm)"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("high (3 g)" = "red", "low (1 g)" = "blue", "none" = "grey"))

pers_controlsnowdepth_all_plot

#transitional control albedo
trans_controlsnowdepth_all_plot <- ggplot() +
  geom_col(data = trans_control_all, aes(x = factor(date), y = mean_snowdepth_bydate, fill = concentration), alpha = 0.4, width = 0.6, position = "dodge") +
  labs(
    #title = "Persistent Control Plots Snow Depth",
    x = "Date of Observation",
    y = "Mean Snow Depth by Concentration (cm)"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("high (3 g)" = "red", "low (1 g)" = "blue", "none" = "grey"))

trans_controlsnowdepth_all_plot
```

```{r}
#combining albedo and snowdepth plots by zone
pers_control_allplots <- pers_controlalb_all_plot + pers_controlsnowdepth_all_plot + plot_layout(nrow = 2)

pers_control_allplots

trans_control_allplots <- trans_controlalb_all_plot + trans_controlsnowdepth_all_plot + plot_layout(nrow = 2)

trans_control_allplots

#Combinging the combined albedo and snowdepth plots
all_control_plots <- ggarrange(
  all_control_albedo_plot, 
  all_control_snowdepth_plots, 
  nrow = 2,              # Arrange in 2 rows
  common.legend = TRUE,  # Share a common legend
  legend = "right"       # Position the legend on the right
)

all_control_plots
```

```{r}
#saving combined plot
ggsave("all_controlplot_albedo_results.png", plot = all_control_plots, width = 10, height = 6, dpi = 300, bg = "white")
```

\*\* made comment here to see if I can get git to connect/push/pull
